# general
set  -g default-terminal "tmux-direct"
set  -g base-index      0
setw -g pane-base-index 0
set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  24
set  -s escape-time       500
set  -g history-limit     1000

# vim mode
set -g status-keys vi
set -g mode-keys   vi

# rebind main key: C-Space
unbind C-b
set -g prefix C-Space
bind -n -N "Send the prefix key through to the application" C-Space send-prefix

# activate clipboard
set -g set-clipboard on

# set split panel to split in CWD
bind ';' split-window -v -c "#{pane_current_path}"
bind ':' split-window -h -c "#{pane_current_path}"

# bind change windows to shift+alt+h/l
bind -n M-H previous-window
bind -n M-L next-window

# renumber windows if a window is closed
set-option -g renumber-windows on
