# general
set  -g default-terminal "tmux-direct"
set  -g base-index      0
setw -g pane-base-index 0
set  -g mouse             on
set  -g focus-events      off
setw -g aggressive-resize off
setw -g clock-mode-style  24
set  -s escape-time       500
set  -g history-limit     1000

# vim mode
set -g status-keys vi
set -g mode-keys   vi

# select panes
bind -n C-h select-pane -L
bind -n C-j select-pane -D
bind -n C-k select-pane -U
bind -n C-l select-pane -R

# resize panes
bind -n M-h resize-pane -L
bind -n M-j resize-pane -D
bind -n M-k resize-pane -U
bind -n M-l resize-pane -R

# rebind main key: C-Space
unbind C-b
set -g prefix C-Space
bind -n -N "Send the prefix key through to the application" C-Space send-prefix

# activate clipboard
set -g set-clipboard on

# set split panel to split in CWD
bind ';' split-window -v -c "#{pane_current_path}"
bind ':' split-window -h -c "#{pane_current_path}"

# bind change windows to shift+alt+h/l
bind -n M-H previous-window
bind -n M-L next-window

# renumber windows if a window is closed
set-option -g renumber-windows on

# pane title
set -g pane-border-status top
set -g pane-border-format " #{pane_index}: #{pane_title} "
set-option -g allow-rename off
unbind C-b
bind "'" command-prompt -p "Pane Title" 'select-pane -T "%%"'
